name: Docker Runner

on:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Create .env
        run: |
          touch .env
          echo DISCORD_APP_ID=${{ secrets.DISCORD_APP_ID }} >> .env
          echo DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }} >> .env
          echo PREFIX=${{ secrets.PREFIX }} >> .env
          cat .env

      - name: Run Container
        run: docker compose up -d --build --force-recreate

      - name: Prune Images
        run: docker image prune -f

      - name: Prune Excess Build Cache
        run: docker buildx prune -f --max-used-space=1gb
